// @vitest-environment node
import {
	existsSync,
	mkdtempSync,
	readdirSync,
	readFileSync,
	rmSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import type { CapturePayload } from "../types";
import { createDevServer, type DevServer } from "./dev-server";
import { handleCapture } from "./handle-capture";

function makePayload(id: string, text = "Hello"): CapturePayload {
	return {
		id,
		timestamp: Date.now(),
		tree: {
			tag: "div",
			className: "card",
			style: { padding: "16px" },
			attributes: {},
			nodeType: "layout",
			children: [
				{
					tag: "h2",
					className: "title",
					style: {},
					attributes: {},
					nodeType: "text",
					textContent: text,
					children: [],
				},
				{
					tag: "p",
					className: "body",
					style: {},
					attributes: {},
					nodeType: "text",
					textContent: "Some description text here",
					children: [],
				},
			],
		},
	};
}

const createdDirs: string[] = [];

function makeTempDir(): string {
	const dir = mkdtempSync(join(tmpdir(), "autoskeleton-integration-"));
	createdDirs.push(dir);
	return dir;
}

afterEach(() => {
	for (const dir of createdDirs) {
		rmSync(dir, { recursive: true, force: true });
	}
	createdDirs.length = 0;
});

describe("handleCapture integration — registry generation", () => {
	it("creates outDir automatically when it does not exist", () => {
		const outDir = join(makeTempDir(), "nested", "skeletons");
		expect(existsSync(outDir)).toBe(false);

		handleCapture(makePayload("user-card"), outDir);

		expect(existsSync(outDir)).toBe(true);
		expect(existsSync(join(outDir, "user-card.tsx"))).toBe(true);
		expect(existsSync(join(outDir, "registry.ts"))).toBe(true);
	});

	it("generates a registry.ts that imports all captured components", () => {
		const outDir = makeTempDir();

		handleCapture(makePayload("user-card"), outDir);
		handleCapture(makePayload("post-card", "Post title"), outDir);
		handleCapture(makePayload("comment-item", "Comment text"), outDir);

		const registry = readFileSync(join(outDir, "registry.ts"), "utf-8");

		// Must import ComponentType from react
		expect(registry).toContain('import type { ComponentType } from "react"');

		// Must import each generated skeleton component
		expect(registry).toContain(
			'import { UserCardSkeleton } from "./user-card"',
		);
		expect(registry).toContain(
			'import { PostCardSkeleton } from "./post-card"',
		);
		expect(registry).toContain(
			'import { CommentItemSkeleton } from "./comment-item"',
		);

		// Must have registry entries for each
		expect(registry).toContain('"user-card": UserCardSkeleton');
		expect(registry).toContain('"post-card": PostCardSkeleton');
		expect(registry).toContain('"comment-item": CommentItemSkeleton');

		// Must export as Record<string, ComponentType<any>>
		expect(registry).toContain("Record<string, ComponentType<any>>");
	});

	it("generates .tsx files that every registry import points to", () => {
		const outDir = makeTempDir();

		handleCapture(makePayload("user-card"), outDir);
		handleCapture(makePayload("post-card", "Post"), outDir);

		const registry = readFileSync(join(outDir, "registry.ts"), "utf-8");

		// Extract all import paths from the registry
		const importRegex = /from "\.\/([^"]+)"/g;
		const importedFiles: string[] = [];
		for (const match of registry.matchAll(importRegex)) {
			importedFiles.push(match[1]);
		}

		expect(importedFiles.length).toBeGreaterThanOrEqual(2);

		// Every imported file must exist as a .tsx file on disk
		for (const file of importedFiles) {
			const filePath = join(outDir, `${file}.tsx`);
			expect(existsSync(filePath), `${filePath} should exist`).toBe(true);
		}
	});

	it("generates valid .tsx component files with export", () => {
		const outDir = makeTempDir();

		handleCapture(makePayload("user-card"), outDir);

		const component = readFileSync(join(outDir, "user-card.tsx"), "utf-8");

		// Must export a named function component
		expect(component).toContain("export function UserCardSkeleton");

		// Must contain the auto-generated comment
		expect(component).toContain("Auto-generated by autoskeleton");

		// Must import React for type annotations
		expect(component).toContain("React");

		// Must contain skeleton-specific attributes
		expect(component).toContain("loaded-skeleton");
		expect(component).toContain('aria-hidden="true"');
	});

	it("keeps registry in sync after removing a skeleton", () => {
		const outDir = makeTempDir();

		handleCapture(makePayload("card-a"), outDir);
		handleCapture(makePayload("card-b"), outDir);

		let registry = readFileSync(join(outDir, "registry.ts"), "utf-8");
		expect(registry).toContain("card-a");
		expect(registry).toContain("card-b");

		// Simulate removing card-a.tsx (like a reset of one skeleton)
		rmSync(join(outDir, "card-a.tsx"));

		// Next capture of card-b should rebuild registry without card-a
		handleCapture(makePayload("card-b"), outDir);

		registry = readFileSync(join(outDir, "registry.ts"), "utf-8");
		expect(registry).not.toContain("card-a");
		expect(registry).toContain("card-b");
	});

	it("includes __captureConfig__ when captureUrl is provided", () => {
		const outDir = makeTempDir();

		handleCapture(makePayload("user-card"), outDir, "http://127.0.0.1:7331");

		const registry = readFileSync(join(outDir, "registry.ts"), "utf-8");
		expect(registry).toContain("__captureConfig__");
		expect(registry).toContain("http://127.0.0.1:7331");
	});

	it("captureUrl must be a base URL without /react-loaded-capture path (client appends it)", () => {
		const outDir = makeTempDir();

		// Simulate what dev-server does: pass base URL only
		handleCapture(makePayload("user-card"), outDir, "http://localhost:7331");

		const registry = readFileSync(join(outDir, "registry.ts"), "utf-8");

		// Extract the URL from __captureConfig__
		const urlMatch = registry.match(/url:\s*"([^"]+)"/);
		expect(urlMatch).not.toBeNull();
		const configUrl = urlMatch?.[1];

		// The URL must NOT end with /react-loaded-capture — client.ts appends it:
		//   fetch(`${captureUrl}/react-loaded-capture`, ...)
		// If captureUrl is "http://localhost:7331/react-loaded-capture", the final URL becomes
		// "http://localhost:7331/react-loaded-capture/react-loaded-capture" → 404
		expect(configUrl).not.toMatch(/\/react-loaded-capture$/);

		// Verify the full endpoint URL the client would build is correct
		const clientEndpoint = `${configUrl}/react-loaded-capture`;
		const parsed = new URL(clientEndpoint);
		expect(parsed.pathname).toBe("/react-loaded-capture");
	});
});

describe("dev-server integration — full HTTP pipeline", () => {
	let server: DevServer;
	let outDir: string;
	let baseUrl: string;

	afterEach(async () => {
		if (server) await server.stop();
	});

	it("creates files on disk when POST /react-loaded-capture is sent", async () => {
		outDir = join(makeTempDir(), "generated", "skeletons");
		server = createDevServer({ port: 0, outDir });
		await server.start();
		baseUrl = `http://localhost:${server.port}`;

		const payload = makePayload("hero-banner", "Welcome to our site");

		const res = await fetch(`${baseUrl}/react-loaded-capture`, {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify(payload),
		});

		expect(res.status).toBe(200);
		const body = await res.json();
		expect(body.result).toBe("generated");

		// Verify files were actually created on disk
		expect(existsSync(join(outDir, "hero-banner.tsx"))).toBe(true);
		expect(existsSync(join(outDir, "registry.ts"))).toBe(true);

		// Verify registry content
		const registry = readFileSync(join(outDir, "registry.ts"), "utf-8");
		expect(registry).toContain("hero-banner");
		expect(registry).toContain("HeroBannerSkeleton");
	});

	it("handles multiple captures via HTTP and builds correct registry", async () => {
		outDir = makeTempDir();
		server = createDevServer({ port: 0, outDir });
		await server.start();
		baseUrl = `http://localhost:${server.port}`;

		// Send two different captures
		for (const id of ["nav-bar", "footer-widget"]) {
			const res = await fetch(`${baseUrl}/react-loaded-capture`, {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify(makePayload(id)),
			});
			expect(res.status).toBe(200);
		}

		// Verify all files
		const files = readdirSync(outDir);
		expect(files).toContain("nav-bar.tsx");
		expect(files).toContain("footer-widget.tsx");
		expect(files).toContain("registry.ts");

		const registry = readFileSync(join(outDir, "registry.ts"), "utf-8");
		expect(registry).toContain('"footer-widget": FooterWidgetSkeleton');
		expect(registry).toContain('"nav-bar": NavBarSkeleton');

		// Verify alphabetical order
		const footerIdx = registry.indexOf("footer-widget");
		const navIdx = registry.indexOf("nav-bar");
		expect(footerIdx).toBeLessThan(navIdx);
	});

	it("writes __captureConfig__ with correct base URL (no double /react-loaded-capture)", async () => {
		outDir = makeTempDir();
		server = createDevServer({ port: 0, outDir });
		await server.start();
		baseUrl = `http://localhost:${server.port}`;

		const res = await fetch(`${baseUrl}/react-loaded-capture`, {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify(makePayload("test-component")),
		});
		expect(res.status).toBe(200);

		const registry = readFileSync(join(outDir, "registry.ts"), "utf-8");
		expect(registry).toContain("__captureConfig__");

		// Extract the URL the dev-server wrote into __captureConfig__
		const urlMatch = registry.match(/url:\s*"([^"]+)"/);
		expect(urlMatch).not.toBeNull();
		const configUrl = urlMatch?.[1];

		// Must NOT contain /react-loaded-capture — the client appends it
		expect(configUrl).not.toMatch(/\/react-loaded-capture/);

		// Must be a valid base URL pointing to the actual server port
		expect(configUrl).toBe(`http://localhost:${server.port}`);

		// Simulate what client.ts does: append /react-loaded-capture and verify it works
		const verifyRes = await fetch(`${configUrl}/react-loaded-capture`, {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify(makePayload("roundtrip-test")),
		});
		expect(verifyRes.status).toBe(200);
		const body = await verifyRes.json();
		expect(body.result).toBe("generated");
	});
});
